### ISSUE TITLE
Marathi Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-mr#1]
## Maintainer List

* @spielers 
* @visshaljagtap 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [ ] community/code-of-conduct
    

### Tutorial

* [x] tutorial/index (@visshaljagtap) #20 
* [ ] tutorial/part-zero(@spielers )
* [ ] tutorial/part-one(@gamitics )
* [x] tutorial/part-two (@spathak98 )
* [x] tutorial/part-three (@abhaypawar) #29
* [ ] tutorial/part-four
* [ ] tutorial/part-five (@ng29) 
* [ ] tutorial/part-six (@Abdulhussainjarif)
* [ ] tutorial/part-seven
* [ ] tutorial/part-eight
    

### Docs

* [x] docs/index (@abhaypawar) #11
* [x] docs/quick-start  (@abhaypawar) #9 
* [x] docs/recipes  (@abhaypawar) 
* [ ] docs/recipes/pages-layouts
* [x] docs/recipes/styling-css (@k-guy-dev )
* [ ] docs/recipes/working-with-starters (@Abdulhussainjarif)
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site
* [ ] docs/api-reference (@Abdulhussainjarif)
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image
* [ ] docs/gatsby-config
* [ ] docs/browser-apis (@kalzen15)
* [ ] docs/ssr-apis
* [x] docs/api-files (@gamitics ) 
* [ ] docs/api-files-gatsby-config (@spielers )
* [x] docs/api-files-gatsby-browser (@spielers) #18 
* [x] docs/api-files-gatsby-node (@gamitics ) #21 
* [x] docs/api-files-gatsby-ssr (@spielers ) #19 
* [x] docs/actions  (@abhaypawar) #12
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model (@Abdulhussainjarif)
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification
* [ ] docs/glossary
* [ ] docs/gatsby-cli

**Comment by visshaljagtap** [comment]
I'm going to start with tutorial/index first. @gamitics and @spielers please take the pages from mentioned list and assign to yourself!

**Comment by visshaljagtap** [comment]
> I'm going to start with tutorial/index first. @gamitics and @spielers please take the pages from mentioned list and assign to yourself!

@gamitics @spielers Requesting you to please mention your name against the page you want to translate in this issue #1 so that we all are on same page

**Comment by abhaypawar** [comment]
Hi, I will be happy helping you translate the docs/quick-start page. I have read all the relevant docs.
@gamitics

**Comment by spielers** [comment]
@abhaypawar go on !!

**Comment by abhaypawar** [comment]
Hi everyone. I have translated two pages and will do the third one in doc section (docs/recipes).
Thanks everyone.

**Comment by abhaypawar** [comment]
Please someone guide me in marking the pages those are translated and merged.  
Thanks

**Comment by visshaljagtap** [comment]
@abhaypawar Thanks for your contribution.

> Hi everyone. I have translated two pages and will do the third one in doc section (docs/recipes).
> Thanks everyone.

@abhaypawar assigned page

**Comment by visshaljagtap** [comment]
> Please someone guide me in marking the pages those are translated and merged.
> Thanks

@abhaypawar Thanks for your valuable contribution. I have assiged your name to pages that your are translating and also added reference. As your docs/quick-start translation is merged, I have marked that page completed.

**Comment by spielers** [comment]
@visshaljagtap Lets pull this translation work within this month I have added new tags. new contributors also can contribute within this month And I request you to review my PR #18

**Comment by spielers** [comment]
@visshaljagtap thanks

**Comment by spielers** [comment]
@gamitics I am assigning you to the part one tutorial

**Comment by spathak98** [comment]
@spielers i want to do this issue(part-two).

**Comment by spielers** [comment]
@spathak98 Go on.

**Comment by spielers** [comment]
@abhaypawar I would suggest you take something from tutorials.

**Comment by abhaypawar** [comment]
That's great. I would do tutorial as its in the order up there. I'll take up the tutorial/part-three.

**Comment by syshcndr** [comment]
Hey! @spielers, I am Interested in translating docs/theme-api which is under Docs. Can you please assign me that.

**Comment by spielers** [comment]
@syshcndr  That would be great, but as of now we need to translate the tutorials first once that all done you can take up the remaining pages. For now, you can take any page from tutorials that are remaining and work on!

Best,
spielers

**Comment by kalzen15** [comment]
Hey @spielers!!!
I would like to work on docs/browser-apis
.

**Comment by spielers** [comment]
Hey, @kalzen15 Ok go for it. will assign your name there.

**Comment by spathak98** [comment]
Hey @spielers I want to do this issue(docs/node-apis).Can you please assign me that.

**Comment by ng29** [comment]
Hey @spielers / @visshaljagtap 
Can i pick up docs/node-api-helpers or docs/node-model to get jumpstart on this list of issue... 
(Please assign any one of above listed)

Cheers.

**Comment by spielers** [comment]
Hey, @ng29 Thanks for your interest but I would suggest you should take something from  `tutorial/..` we have to complete that first,

Best
spielers

**Comment by ng29** [comment]
> Hey, @ng29 Thanks for your interest but I would suggest you should take something from `tutorial/..` we have to complete that first,
> 
> Best
> spielers

Sure, please assign me  tutorial/part-five 👍

**Comment by spathak98** [comment]
Hey @spielers I have updated docs/node-model. Please look into it.

**Comment by k-guy-dev** [comment]
Hey @spielers ! I would like to work on docs/recipes/styling-css

**Comment by spielers** [comment]
> Hey @spielers ! I would like to work on docs/recipes/styling-css

Sure, @k-guy-dev I will assign that to you!

Best,
spielers

**Comment by Abdulhussainjarif** [comment]
@spielers Please assign me tutorial/part-six

**Comment by spielers** [comment]
Ok, @Abdulhussainjarif  Sure!

**Comment by Abdulhussainjarif** [comment]
@spielers Can you please assign me docs/recipes/working-with-starters

**Comment by spielers** [comment]
@Abdulhussainjarif  sure go ahead!

**Comment by Abdulhussainjarif** [comment]
@spielers Please assign me, docs/api-reference

**Comment by Abdulhussainjarif** [comment]
@spielers Hii, can you please assign me, docs/node-model?

**Comment by spielers** [comment]
> @spielers Hii, can you please assign me, docs/node-model?

Hey @Abdulhussainjarif  You can start working on it, 

best,
spielers
